### ISSUE TITLE
nj 添加页面的时候，文件夹大小写问题

### ISSUE THREAD

**Issue by jianpingqiu** [joe-sky/nornj-cli#5]
OS ：  linux
nj 执行自动新增页面，生成的文件夹名称大小写问题，建议全部小写

**Comment by joe-sky** [comment]
@jianpingqiu 能否具体给下在`linux`中文件夹名中有大写会带来的问题都有哪些？

`nornj-cli`生成的有大写字母的目录都是`camel命名法`的，我暂时了解到的全改为小写的好处就是这些：http://www.ruanyifeng.com/blog/2017/02/filename-should-be-lowercase.html

另外生成的文件名也有含大写的，看了下`vue-cli`的模板，它生成的项目里面也有大写命名的文件：https://github.com/vuejs-templates/webpack/blob/develop/template/src/components/HelloWorld.vue

望指教，多谢:neutral_face:

**Comment by rfox00** [comment]
linux大小写敏感，文件互相引用的时候如果没有一个统一的命名规则，会显得混乱，比如编译报错之类的。不严重，但烦人。

**Comment by joe-sky** [comment]
@rfox00 同感，我也特意调研了下这个问题，看了一些比较著名的框架代码中是怎么处理目录名大小写问题的：

1. [ant design](https://github.com/ant-design/ant-design/tree/master/components)的目录名遵循全部小写，但是组件文件名全部大写开头；
2. [element-ui](https://github.com/ElemeFE/element/tree/dev/packages)的目录名和组件文件名都是遵循全部小写；
3. [material-ui](https://github.com/mui-org/material-ui/tree/master/packages/material-ui/src)的组件目录和组件文件名都是大写开头；

由此也可以看出，**目录和文件名大小写似乎没有统一规定到底时大写还是小写合适**；但是，**每个项目应有它统一的规定哪些文件该大小及哪些文件该小写**。

其实`NornJ-cli`的文件命名目前也算是有规范的，比如目前目录名用的是`camel命名法`，组件文件名规定首字母大写等；日后是有必要在文档中写一下相关目录及文件名的大小写规范。
