### ISSUE TITLE
请问创建的项目怎么使用nginx进行部署

### ISSUE THREAD

**Issue by pp-ball** [joe-sky/nornj-cli#6]
请问创建的项目怎么使用nginx进行部署

**Comment by rfox00** [comment]
nornj-cli本身不包含nginx，所以不知道你这问题是指开发环境还是生产环境。

说说我们这边本地怎么弄的吧，前提是懂一些nginx配置。
首先，在用nornj-cli创建的前端项目根目录运行npm run build 或 yarn run build，生成dist；
然后，分两种情况
第一种，把生成的dist放到nginx默认webroot里，可以手工拷贝，也可以让webpack自动处理；
第二种，改nginx配置，在nginx.conf中，把webroot 改成dist所在目录；
不管哪种，都重启下nginx
最后，打开浏览器看看效果，具体URL要看nginx是怎么配置的。
以上是本地环境开发用，这里的nginx作为web服务使用。

还有一种情况是web服务由前端承担，nginx只做代理转发，这个模式在开发过程中也很常见：
首先，启动web服务 npm start 或 yarn start，默认地址是http://localhost:8080/dist/xxx...；
然后，配置nginx，
1. 新增upstream portaldist，将此upstream里的server值改为 localhost:8080；
2. 转发规则里新增 location /dist，将porxy_pass改为 http://portaldist
退出配置文件，重启nginx。
打开浏览器，访问http://localhost（根据nginx实际配置更改）。
