### ISSUE TITLE
请问项目如何打包后在服务器上部署？

### ISSUE THREAD

**Issue by JSMengLingqi** [joe-sky/nornj-cli#7]

**Comment by joe-sky** [comment]
以[这个项目模板](https://github.com/joe-sky/nornj-cli/tree/master/templates/react-mst-universal)为例：

1. 执行`npm run build`命令后会生成一个`dist`目录，这就是要部署的前端代码。
2. 把`dist`目录复制到要部署的web项目中(例如一个基于java相关技术的web项目)。
3. 在web项目中把首页的`controller`指向`dist/web/index.html`即可。另外需要确保前端代码中各种请求的域名及路径与web项目是匹配的，可能还需要改一些webpack配置参数，比如[这里](https://github.com/joe-sky/nornj-cli/blob/master/templates/react-mst-universal/webpack.config.js#L297)。

部署这块暂时没有做太多自动化的东西，我们这边一般也可能会这样做：

把前端和java的web项目建在同一工程目录内，然后修改前端webpack的打包路径直接把`dist`打包到java的web项目中，在把路径什么的配置正确就可以了。
